openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8081'
    description: Generated server url
paths:
  /datasets:
    get:
      tags:
        - dataset-controller
      operationId: all
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CollectionModelEntityModelDataset'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - dataset-controller
      operationId: newDataset
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                dataset:
                  $ref: '#/components/schemas/Dataset'
                file:
                  type: string
                  format: binary
              required:
                - dataset
                - file
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  '/datasets/{id}':
    get:
      tags:
        - dataset-controller
      operationId: one
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EntityModelDataset'
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  '/datasets/{id}/file':
    get:
      tags:
        - dataset-controller
      operationId: downloadFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
  '/datasets/{id}/delete':
    delete:
      tags:
        - dataset-controller
      operationId: delete
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: object
        '404':
          description: Not Found
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Dataset:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          minLength: 1
        description:
          type: string
        fileFormat:
          type: string
          enum:
            - CSV
            - JSON
        size:
          type: integer
          format: int64
        numEntries:
          type: integer
          format: int64
        originalFilename:
          type: string
        hash:
          type: string
        createdAt:
          type: string
          format: date-time
        savedAt:
          type: integer
          format: int64
        delim:
          type: string
        header:
          type: boolean
        numAttributes:
          type: integer
          format: int32
      required:
        - fileFormat
        - name
    CollectionModelEntityModelDataset:
      type: object
      properties:
        _embedded:
          type: object
          properties:
            datasetList:
              type: array
              items:
                $ref: '#/components/schemas/EntityModelDataset'
        _links:
          $ref: '#/components/schemas/Links'
    EntityModelDataset:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          minLength: 1
        description:
          type: string
        fileFormat:
          type: string
          enum:
            - CSV
            - JSON
        size:
          type: integer
          format: int64
        numEntries:
          type: integer
          format: int64
        originalFilename:
          type: string
        hash:
          type: string
        createdAt:
          type: string
          format: date-time
        savedAt:
          type: integer
          format: int64
        delim:
          type: string
        header:
          type: boolean
        numAttributes:
          type: integer
          format: int32
        _links:
          $ref: '#/components/schemas/Links'
      required:
        - fileFormat
        - name
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
    Links:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Link'
